digipost/digipost-api-client-java

src/main/java/no/digipost/api/client/ApiService.java
src/main/java/no/digipost/api/client/ApiServiceImpl.java
src/main/java/no/digipost/api/client/ApiServiceMock.java
src/main/java/no/digipost/api/client/Communicator.java
src/main/java/no/digipost/api/client/DigipostClient.java
src/main/java/no/digipost/api/client/DigipostClientMock.java
src/main/java/no/digipost/api/client/DocumentCommunicator.java
src/main/java/no/digipost/api/client/errorhandling/DigipostClientException.java
src/main/java/no/digipost/api/client/errorhandling/ErrorCode.java
src/main/java/no/digipost/api/client/representations/Channel.java
src/main/java/no/digipost/api/client/representations/DeliveryStatus.java
src/main/java/no/digipost/api/client/representations/DocumentStatus.java
src/main/java/no/digipost/api/client/representations/ErrorMessage.java
src/main/java/no/digipost/api/client/representations/HashAlgorithm.java
src/main/java/no/digipost/api/client/representations/ObjectFactory.java
src/main/java/no/digipost/api/client/representations/Read.java
src/main/java/no/digipost/api/client/representations/xml/DateTimeXmlAdapter.java
src/main/resources/xsd/api_v6.xsd
src/test/java/no/digipost/api/client/representations/XsdValidationTest.java

Support for fetching document-status for previously sent document.

---

.editorconfig

Using tabs for indentation since that's what existing code uses.
Ok @velfundert?

Adds editorconfig to standardize indentation style

---

src/main/java/no/digipost/api/client/userdocuments/ApiService.java
src/main/java/no/digipost/api/client/userdocuments/BankAccountNumber.java
src/main/java/no/digipost/api/client/userdocuments/DigipostUserDocumentClient.java
src/main/java/no/digipost/api/client/userdocuments/InvoicePayment.java

stuff for updateInvoice-kall. Bruker `<invoice-payment />` for å oppdatere.

User documents update invoice

---

src/main/java/no/digipost/api/client/userdocuments/Error.java
src/main/java/no/digipost/api/client/userdocuments/ErrorCode.java
src/main/java/no/digipost/api/client/userdocuments/ServerSignatureException.java

Unknown codes are parsed to GENERAL_ERROR

Switched back to using enum for error codes

---

src/main/java/no/digipost/api/client/userdocuments/Attribute.java
src/main/java/no/digipost/api/client/userdocuments/Attributes.java
src/main/java/no/digipost/api/client/userdocuments/Document.java
src/main/java/no/digipost/api/client/userdocuments/Documents.java
src/main/java/no/digipost/api/client/userdocuments/Invoice.java

Added senderName property to Document.
... and toString() to Document, Attribute and Invoice

Added senderName to Document

---

src/main/java/no/digipost/api/client/ApiServiceImpl.java
src/main/java/no/digipost/api/client/DigipostClient.java
src/main/java/no/digipost/api/client/userdocuments/ApiService.java
src/main/java/no/digipost/api/client/userdocuments/DigipostUserDocumentClient.java
src/main/java/no/digipost/api/client/userdocuments/DocumentContent.java
src/main/java/no/digipost/api/client/userdocuments/InvoiceUpdate.java

Support for getting pdf/html link for a Document:
See:
* `DigipostUserDocumentClient.getDocumentContent(...)`
* `DocumentContent`

Support for getting pdf/html link for a Document

---

src/main/java/no/digipost/api/client/ApiServiceImpl.java
src/main/java/no/digipost/api/client/DigipostClient.java
src/main/java/no/digipost/api/client/DigipostClientMock.java

Hovedsakelig denne: https://github.com/digipost/digipost-api-client-java/pull/31/files#r104433488
Det andre er bare fluff.

Fikser uriktig bruk av setPath ved URI-bygging

---

inbox-api-specification.md

Typos in inbox spec

---

src/main/java/no/digipost/api/client/DigipostClientMock.java

Denne ga compiler error i Eclipse. Dukket nok opp i.f.m. en merge. Gidder du bare å klikke approve på den, @froden f.eks.?

Rydder vekk 3x import av samme klasse

---

pom.xml
src/main/java/no/digipost/api/client/representations/sender/SenderFeatureName.java
src/main/java/no/digipost/api/client/representations/sender/SenderInformation.java

Brukar den nya printability validatorn
https://github.com/digipost/printability-validator/pull/6

Use the new printability validator that supports inward bleeding

---

pom.xml
src/main/java/no/digipost/api/client/representations/inbox/Inbox.java
src/main/java/no/digipost/api/client/representations/inbox/package-info.java

Fikser bug som forhindrer brukere av klientbiblioteket med nyere versjon av Java å ikke kunne hente ut innboksen.

Kan ikke hente innboks med nyere Java

---

docs/_v8_0/2_receive.md

Adds better documentation for inbox

---

docs/_v9_0/1_send.md
docs/_v9_0/2_receive.md
docs/_v9_0/index.html

- fjerner ugyldig dokumentasjon av bruk av datatypes fra v8
- full dokumentasjon for v9 inkl. bruk av datatyps

oppdaterer dokumentasjonen til å stemme overens med versjon 9 av klienten

---

docs/_config.yml

For å aktivere 9.0-dokumentasjonen 👍

Enable latest docs v9.0

---

docs/_v9_0/1_send.md

Expands the text explaining datatypes.

add more verbose explanation of what datatypes are

---

pom.xml

Appointment har fått flere felter for å kunne understøtte at denne typen kan brukes til Valgkortutsending.
Med det samme oppdaterte jeg diverse avhengigheter.

Oppdaterer data-typer

---

src/main/java/no/digipost/api/client/representations/Document.java
src/test/java/no/digipost/api/client/representations/DocumentTest.java

Resolves  [#95](https://github.com/digipost/digipost-api-client-java/issues/95)

Fix boolean comparison for Document opened property

---

src/main/java/no/digipost/api/client/representations/DocumentEventType.java
src/main/resources/xsd/api_v7.xsd

Legger til nye dokumentevent-typer for epostmelding sendt via api

legg til nye dokument-event-typer for epost-melding via api

---

NOTICE
pom.xml
src/test/java/no/digipost/api/client/eksempelkode/GithubPagesSendExamples.java

Also bump data-types.
Resolves #120

Bump html-validator with newest owasp-java-html-sanitizer.

---

src/main/java/no/digipost/api/client/internal/delivery/MessageDeliverer.java

The case this tries to address is where you have some type of looping to add attachments, or maby the missing of this looping. It might be easy to forget to go from a non looping code to a looping code that you need to add all the attachments and also all the actual files.

Warn if you add more filer/attachments to a message without having them specified in the actual message

---

src/main/resources/xsd/api_v8.xsd

This brings some API changes to our new, experimental upcoming feature.

Update API: print-if-not-registered -> request-for-registration

---

src/main/java/no/digipost/api/client/representations/sender/SenderFeature.java
src/main/java/no/digipost/api/client/representations/sender/SenderFeatureName.java

Can a sender leave out KID?
What filetypes can be sent?
How big can the files be?

Features of Digipost-validation

---

docs/_v16_x/4_archive.md
src/main/java/no/digipost/api/client/representations/archive/Archive.java
src/main/java/no/digipost/api/client/representations/archive/ArchiveDocument.java
src/test/java/no/digipost/api/client/eksempelkode/GithubPagesArchiveExamples.java

There are 4 search-options now:
* get all
* by attributes
* by date
* by date and attributes

Add search archive documents by date
