digipost/digipost-api-client-java

pom.xml
src/main/java/no/digipost/api/client/DocumentsPreparer.java
src/main/java/no/digipost/api/client/MessageSender.java
src/main/java/no/digipost/api/client/delivery/AtomicPrintOnlyMessage.java
src/main/java/no/digipost/api/client/delivery/AtomicWithPrintFallback.java
src/main/java/no/digipost/api/client/delivery/DocumentContent.java
src/main/java/no/digipost/api/client/representations/Document.java
src/main/java/no/digipost/api/client/representations/IdentificationResultWithEncryptionKey.java
src/main/java/no/digipost/api/client/representations/Message.java
src/main/java/no/digipost/api/client/representations/MessageRecipient.java
src/test/java/no/digipost/api/client/MessageSenderTest.java
src/test/java/no/digipost/api/client/representations/DocumentTest.java
src/test/java/no/digipost/api/client/representations/MessageTest.java

Denna branchen tillåter atomic att skicka olika content (InputStreams) nær man anvænder fallback till print. Ett exempel ær att skicka html till digipost brukare och pdf som printas om en brukare inte finnes i systemet.

Atomic with different content

---

src/main/java/no/digipost/api/client/representations/Document.java
src/main/java/no/digipost/api/client/representations/FileType.java
src/main/java/no/digipost/api/client/representations/Invoice.java
src/test/java/no/digipost/api/client/representations/DocumentTest.java
src/test/java/no/digipost/api/client/representations/MessageTest.java
src/test/java/no/digipost/api/client/representations/XsdValidationTest.java

För att tillåta support av EHF fakturor i MF-adapter så krävs det att Document kan ha flera tekniska vedlegg.
Jag vill ha en ny filtyp för att vara lite ryddig och skilja ut själva original EHF som ska gå in och sparas i digipost.
Eftersom Offentliga nu ska kunna skicka fakturor (Har inte varit möjligt innan såvitt jag vet), så krävs det också att FLYTTET_POST också kan komma vara fakturor. Därför måste jag kunna skapa en faktura som varit opened innan och har därför ändrat konstruktorn.

EHF-support och multipla tekniska typer tillåtna

---

src/main/java/no/digipost/api/client/userdocuments/ApiService.java
src/main/java/no/digipost/api/client/userdocuments/DigipostUserDocumentClient.java
src/main/java/no/digipost/api/client/userdocuments/Error.java
src/main/java/no/digipost/api/client/userdocuments/GetAgreementResult.java
src/main/java/no/digipost/api/client/userdocuments/Result.java
src/main/java/no/digipost/api/client/userdocuments/RuntimeIOException.java
src/main/java/no/digipost/api/client/userdocuments/UnexpectedResponseException.java
src/main/java/no/digipost/api/client/userdocuments/UserDocumentsApiException.java
src/test/java/no/digipost/api/client/userdocuments/Examples.java
src/test/java/no/digipost/api/client/userdocuments/ResultTest.java

GetAgreements now returns a [GetAgreementResult](https://github.com/digipost/digipost-api-client-java/blob/user-documents-getagreement/src/main/java/no/digipost/api/client/userdocuments/GetAgreementResult.java) that contains an Agreement upon success or a reason why the agreement was not found:
* UNKNOWN_USER - UserId (fødselsnummer) is not a Digipost user
* NO_AGREEMENT  - UserId is a Digipost user but no agreement found for that user
* AGREEMENT_DELETED - UserId is a Digipost user and the user has deleted a previous agreement
The following principle is now implemented: For all expected responses be that `200 Ok` or `404 Not found` the client API methods should return normally with a result containing enough information for the client handle it. For all other responses a …

Improved GetAgreements and error handling

---

src/main/java/no/digipost/api/client/DigipostClient.java
src/main/java/no/digipost/api/client/filters/response/ResponseContentSHA256Interceptor.java
src/main/java/no/digipost/api/client/filters/response/ResponseDateInterceptor.java
src/main/java/no/digipost/api/client/filters/response/ResponseSignatureInterceptor.java
src/main/java/no/digipost/api/client/userdocuments/DigipostUserDocumentClient.java
src/test/java/no/digipost/api/client/filters/response/ResponseDateInterceptorTest.java
src/test/java/no/digipost/api/client/filters/response/ResponseSignatureFilterTest.java

Removes complex exception handling in response filters. The filters used to catch all RuntimeExceptions and each has some logic to determine if it was to just log it, rethrow it or unwrap and rethrow. This seemed unnecessary complex.
The option to log instead of throw has been removed. There is no other way to signal an error in the filters than by throwing and exception. Therefore the option didn't make any sense.

User documents filter exceptions

---

src/main/java/no/digipost/api/client/userdocuments/ApiService.java
src/main/java/no/digipost/api/client/userdocuments/DigipostUserDocumentClient.java
src/main/java/no/digipost/api/client/userdocuments/InvoicePayment.java
src/main/java/no/digipost/api/client/userdocuments/InvoiceStatus.java
src/main/java/no/digipost/api/client/userdocuments/InvoiceUpdate.java

Laget et InvoiceUpdate-objekt i tråd med apiet, og et InvoicePayment-objekt for å tvinge brukeren til å bruke gyldige typer. ApiService har en api-compliant updateInvoice-metode, mens klienten har to strengere metoder: payInvoice og deleteInvoice.

updateInvoice med InvoicePayment eller delete-operasjon

---

src/main/java/no/digipost/api/client/filters/request/RequestSignatureInterceptor.java
src/main/java/no/digipost/api/client/filters/response/LoggingClientResponseInterceptor.java
src/main/java/no/digipost/api/client/filters/response/ResponseContentSHA256Interceptor.java

Bruke EntityUtils.toByteArray i stedet for IOUtils for å
sikre at entity-stream closes.

Bedre ressurshåndtering ved konsumering av entity-stream

---

pom.xml
src/main/java/no/digipost/api/client/ApiServiceImpl.java

Etter byttet fra Joda-time til Java-time ble datoer formatert med
patternet `yyyy-MM-dd'T'HH:mm:ss.SSSZZ` litt ulike. Kolonet i offset ble
borte, slik at vi fikk
`2017-03-09T15:34:12.478+0100`
i stedet for
`2017-03-09T15:34:12.248+01:00`
Regexet som brukes i modsecurity i wafen krever det siste kolonet,
dermed fikk vi mye warnings.
Vi bruker nå i stedet `DateTimeFormatter.ISO_OFFSET_DATE_TIME`, og alt er
good.
_For spesielt interesserte_: Skal man fikse dette manuelt uten å bruke
format-konstanten fra DateTimeFormatter, kan man bruke patternet
`yyyy-MM-dd'T'HH:mm:ss.SSSXXX`.

Bruk riktig datoformat mot dpost-api

---

src/main/java/no/digipost/api/client/ApiServiceImpl.java

Jeg trodde dette var fiksa i 59caeb5737e45a15e11, men den gang ei.
DateTimeFormatter.ISO_OFFSET_DATE_TIME gir riktig format, unntatt om
antall miilisekunder er 0. Da dropper den millisekundene fullstendig,
slik at man står igjen med 2017-03-09T15:34:12+01:00, hvilket gir
valideringsfeil backend i dpost-api, slik at requestene gir 400. Da er
vi worse off, ettersom det forrige feilaktige formatet ga oss
200-responser, men med warnings fra WAF-en.
Anyways. Det nye formatet skal funke, og alltid gi datoer på formatet
2017-03-09T15:34:12.248+01:00
uansett om vi har millisekunder eller ikke.

Riktig format på datoer mot dpost-api

---

pom.xml
src/main/java/no/digipost/api/client/util/JAXBContextUtils.java

Missing class causes unmarshal exception for all identification calls:
```
javax.xml.bind.UnmarshalException: unexpected element (uri:"http://api.digipost.no/schema/v7", local:"identification-result").
Expected elements are <{http://api.digipost.no/schema/v7}identification>
```
FIX: Add class to correct jaxb-context

[BUG] Missing IdentificationResult.class in JAXBContext

---

pom.xml
src/main/java/no/digipost/api/client/DigipostClientMock.java
src/main/java/no/digipost/api/client/MessageSender.java
src/main/java/no/digipost/api/client/util/DigipostApiMock.java

Use the parsing facility of Undertow to parse multipart requests in the Digipost mock instead of the ad-hoc flaky substring matching.
It is now possible to retrieve the actual content parts of a sent request, not just the content type.

Use undertow multipart API in digipost mock

---

pom.xml
src/main/java/no/digipost/api/client/MessageSender.java

Content-Transfer-Encoding headeren var ikke nødvendig for at Undertow-mocken skulle bruke riktig encoding for message-delen av multipart-requests.
Enda bedre er at når jeg fjerner Content-Transfer-Encoding så fungerer klientbiblioteket mot Digipost 🙈

Multipart encoding bugfix

---

NOTICE
pom.xml
src/main/java/no/digipost/api/client/representations/PrintDetails.java
src/main/java/no/digipost/api/client/swing/DigipostSwingClient.java
src/test/java/no/digipost/api/client/DocumentsPreparerTest.java
src/test/java/no/digipost/api/client/MessageSenderTest.java
src/test/java/no/digipost/api/client/eksempelkode/FallbackTilPrintEksempel.java
src/test/java/no/digipost/api/client/eksempelkode/GithubPagesSendExamples.java
src/test/java/no/digipost/api/client/representations/MessageTest.java
src/test/java/no/digipost/api/client/representations/ObjectBuilder.java
src/test/java/no/digipost/api/client/representations/XsdValidationTest.java

As of 2018, Posten is no longer separating between A and B priority mail. `post-type` will eventually be removed from the API. For now, `print-details` gets a hardcoded `"A"` as `post-type` until an updated XSD is available, but it is ignored by Digipost.
This will become a `v10`-release, as the Java API is changed to not include PostType.

Remove PostType enum and usage

---

pom.xml
src/main/java/no/digipost/api/client/ApiServiceImpl.java
src/main/java/no/digipost/api/client/representations/Recipient.java
src/main/java/no/digipost/api/client/representations/Recipients.java
src/main/java/no/digipost/api/client/security/ClientRequestToSign.java
src/main/java/no/digipost/api/client/util/ExceptionUtils.java
src/main/java/no/digipost/api/client/util/JAXBContextUtils.java

Since search queries are part of the URL they must be encoded in accordance with [rfc1738](https://tools.ietf.org/html/rfc1738)
This PR fixes both the url-encoding and using the encoded url in the signature.

Correct encoding of search string in URL-path and signature

---

pom.xml
src/main/java/no/digipost/api/client/representations/accounts/EncryptionKey.java
src/main/java/no/digipost/api/client/representations/accounts/UserAccount.java
src/main/resources/xsd/api_v7.xsd

Changes:
* Remove keyId from UserAccount -> EncryptionKey (unused)
- Results in a new type so that it does not interfere with other uses of the other EncryptionKey type
* Remove unused parameters from UserAccount constructor

Bugfix and remove keyId from user account encryption key

---

pom.xml
src/main/java/no/digipost/api/client/DigipostClientMock.java

Dette fører til at vi får `null` når vi henter ut keystoret på JDK10 😔

Fjerner unødvendig kall til `getClass()`

---

pom.xml

To avoid unnecessary transitive dependency.
Used only by highly experimental DigipostApiMock.

Change Undertow dependency to optional

---

.github/workflows/build.yml
.github/workflows/release.yml
pom.xml

Grunnen er at vi må ha siste versjon av parent pom
for å få med pinentry loopback for å hente ut gpg-nøkkel for å signere releaser

Ta i bruk siste super pom og siste versjon av action-maven-publish

---

src/main/java/no/digipost/api/client/DigipostClient.java
src/main/java/no/digipost/api/client/document/DocumentApi.java
src/main/java/no/digipost/api/client/internal/ApiServiceImpl.java
src/main/java/no/digipost/api/client/representations/DeliveryStatus.java
src/main/resources/xsd/api_v7.xsd

Added support for retrieving peppol message status from Digipost. Need this functionality as a part of fallback solution when sending Peppol messages.

Support for retrieving peppol message status from Digipost

---

src/main/java/no/digipost/api/client/representations/EmailDetails.java
src/main/java/no/digipost/api/client/representations/Message.java
src/main/java/no/digipost/api/client/representations/MessageRecipient.java
src/main/resources/xsd/api_v7.xsd
src/test/java/no/digipost/api/client/representations/MessageTest.java

In certain cases senders need to be able to request sending of email message through the Digipost API.
Are the fields in EmailDetails sufficient, or are we missing something?

Added email recipient in message

---

src/main/java/no/digipost/api/client/representations/FailedPeppolMetadata.java
src/main/resources/xsd/api_v7.xsd

legger til PeppolFailedMetadata dokument-event-metadata  (dette skulle vært gjort ifb. adding av dokumenteventypene for Peppol

add peppolfailedmetadata documenteventmetadata

---

pom.xml

Includes pdfbox v2.0.24.
```
--- maven-dependency-plugin:3.1.2:tree (default-cli) @ digipost-api-client-java ---
no.digipost:digipost-api-client-java:jar:14.1-SNAPSHOT
+- no.digipost:printability-validator:jar:3.2:compile
|  \- org.apache.pdfbox:pdfbox:jar:2.0.24:compile
|     \- org.apache.pdfbox:fontbox:jar:2.0.24:compile
```
Resolves #121

Bump printability-validator

---

src/main/java/no/digipost/api/client/internal/Cached.java

1 hour regardless of use. We see that clients using frequent requests
never expires the cache and that can cause problems if the cache is
in a never expire state.

Fixes so that cachees that is used a lot will invalidate after

---

src/main/java/no/digipost/api/client/internal/delivery/DocumentsPreparer.java
src/test/java/no/digipost/api/client/internal/delivery/DocumentsPreparerTest.java

since it contains the entire sanitized contents, which might disclose sensitive data. Instead, explain that you can run DigipostValidatingHtmlSanitizer to view the sanitized result.

Don't dump html validation results on sanitation difference

---

pom.xml

(jackson, commons-codec, jakarta.el) Update to latest non-vulnerable release.
(maven-enforcer-plugin) Upgrade to latest release. Add en
execution of the banVulnerable rule to detect vulnerabilities at build
time.

Update vulnerable dependencies found by Sonatype Lift

---

pom.xml

Exclude reported vulnerability in com.guava.guava:guava.
- https://github.com/google/guava/issues/4011
- https://ossindex.sonatype.org/vulnerability/sonatype-2020-0926?component-type=maven&component-name=com.google.guava/guava
Google has resolved the issue and stated it is "intended functionality". The vulnerability concerns usage of deprecated Files::createTempDir, which creates a temp directory with read access for all users.

Exclude guava vulnerability from scan

---

src/main/java/no/digipost/api/client/representations/EmailDeliveredMetadata.java
src/main/java/no/digipost/api/client/representations/EventMetadata.java
src/main/resources/xsd/api_v8.xsd
src/test/java/no/digipost/api/client/representations/XsdValidationTest.java

Add EmailDeliveredMetadata-type from updated xsd v8. 
DocumentEvents of type EMAIL_MESSAGE_SENT may include this metadata, containing email address.

Update xsd v8

---

docs/_v15_x/4_archive.md
pom.xml
src/main/java/no/digipost/api/client/DigipostClient.java
src/main/java/no/digipost/api/client/archive/ArchiveApi.java
src/main/java/no/digipost/api/client/internal/ApiServiceImpl.java
src/main/java/no/digipost/api/client/representations/Relation.java
src/main/java/no/digipost/api/client/representations/archive/Archive.java
src/main/java/no/digipost/api/client/representations/archive/ArchiveDocument.java
src/main/java/no/digipost/api/client/representations/archive/ArchiveDocumentAttribute.java
src/main/java/no/digipost/api/client/representations/archive/Archives.java
src/main/resources/xsd/api_v8.xsd
src/test/java/no/digipost/api/client/eksempelkode/ArkiverDokumenterEksempel.java
src/test/java/no/digipost/api/client/representations/archive/ArchiveDocumentTest.java

You can now add, update and query archive documents attributes to build better processes archive documents.

Add functionality to use archve document attributes.

---

src/main/java/no/digipost/api/client/DigipostClient.java
src/main/java/no/digipost/api/client/internal/ApiServiceImpl.java
src/main/java/no/digipost/api/client/representations/EntryPoint.java
src/main/java/no/digipost/api/client/representations/Relation.java
src/main/java/no/digipost/api/client/representations/accounts/PublicMailboxTag.java
src/main/java/no/digipost/api/client/representations/accounts/Tag.java
src/main/java/no/digipost/api/client/tag/TagApi.java
src/main/java/no/digipost/api/client/util/JAXBContextUtils.java
src/main/resources/xsd/api_v8.xsd
src/test/java/no/digipost/api/client/eksempelkode/AddTagEksempel.java

In the future, we want to expand this so that senders can manage various settings for their customers. For now, it only supports PublicMailboxTag, which is used to indicate whether a user should receive public mail or not, and is only available for Digdir in the context of managing public mailboxes.

Add and remove tags for user accounts

---

src/main/java/no/digipost/api/client/DigipostClient.java
src/main/java/no/digipost/api/client/internal/ApiServiceImpl.java
src/main/java/no/digipost/api/client/representations/EntryPoint.java
src/main/java/no/digipost/api/client/representations/Relation.java
src/main/java/no/digipost/api/client/representations/accounts/TagType.java
src/main/java/no/digipost/api/client/representations/accounts/Tags.java
src/main/java/no/digipost/api/client/tag/TagApi.java
src/main/resources/xsd/api_v8.xsd

Using this feature requires the ADMINISTER_TAGS Digipost API permission. It can be used to list all current tags for a user, which as for now only covers whether the user receives public mail or not. Filter the resulting list using the TagType enum to derive desired user properties. This functionality is as of yet primarily used for Digdir/KRR to manage public mail recipients.

Method to get list of tags for user, using personal identification number

---

pom.xml
src/main/java/no/digipost/api/client/internal/delivery/DocumentsPreparer.java
src/main/java/no/digipost/api/client/internal/delivery/MessageDeliverer.java
src/main/java/no/digipost/api/client/representations/Message.java
src/test/java/no/digipost/api/client/internal/delivery/MessageDelivererTest.java
src/test/java/no/digipost/api/client/representations/MessageTest.java

This fixes a bug where all ids (digipost address, pin, name and addres and organisation number) gets removed before sending to the api. The result was that the API got a direct print message, even if it was originally a print fallback message, thus returning errors if the sender was not allowed to use direct print.
(Message.copyMessageWithOnlyPrintDetails,
MessageDeliverer.setMapAndMessageToPrint) Copy all fields of the input message (was: omitting ids and a few other fields). Rename to copyPrintMessage, since it no longer narrows the result to print details. Doc fix.

Don't remove digipost id from print messages

---

src/main/java/no/digipost/api/client/representations/Message.java
src/main/java/no/digipost/api/client/representations/RequestForRegistration.java
src/test/java/no/digipost/api/client/internal/delivery/MessageDelivererTest.java
src/test/java/no/digipost/api/client/representations/MessageTest.java

This should have been included with commit
220aa7bd1e30e7bd96032dcbc5ac650e03c93f3b but was overseen.

Rename PrintIfNotRegistered resources to RequestForRegistration

---

src/main/java/no/digipost/api/client/representations/sender/SenderInformation.java
src/test/java/no/digipost/api/client/representations/sender/SenderInformationTest.java

When supportedFeatures == null the for loop will cause a NpE. This happens if NO_INFO_AVAILABLE is the SenderStatus.
This a usage of `sendClient.getSenderInformation(SenderId.of(1030)).hasEnabled(SenderFeatureName.DIGIPOST_DELIVERY);` could result in NpE instead of `false` as would be expected

Add guard to remove a possible NullpointerException

---

docs/_v15_x/1_client_config.md

It's hard to keep the version number updated, so let's not try.
central.sonatype.com is taking over from search.maven.org, so I have updated the link.
https://central.sonatype.org/faq/what-happened-to-search-maven-org/

Remove version from installation guide, refer to Sonatype

---

src/main/java/no/digipost/api/client/errorhandling/ErrorCode.java

This eliminates the need to parse the error message from a general error, when the api returns an error on a non-existing batch.

Add error code to indicate batch not found

---

src/main/java/no/digipost/api/client/errorhandling/ErrorCode.java

This is _not_ the same as `UNKNOWN_USER_ID`, which is used when the `X_Digipost_UserId` header is missing.

Add ErrorCode returned from the API when accessing resources with unknown users in request body

---

docs/Gemfile.lock
pom.xml

Fixes vulnerabilities in gems.
Had to add .ruby-version for `bundle install` to work. Used the same
ruby version as specified in https://pages.github.com/versions.json,
which is linked from Gemfile.

Dependency upgrades

---

docs/Gemfile
docs/Gemfile.lock

Måtte skrive om open() i Gemfile for å matche ruby 3 syntaks. La til activesupport eksplisitt fordi den downgradet seg ved oppdatering til ruby 3.3.0. Nokogiri er også oppdatert for å patche en CVE.

Bundle med ruby 3 og bump activesupport
